### ISSUE TITLE
Escape Artist

### ISSUE THREAD

**Issue by welo1997** [Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK#8]
Hello, thank you for this addon, its very useful. I have one slight issue

On a server where the spell Escape Artist isnt instant, but instead 0.5 sec cast, it doesnt show on the cd bars, even though the spellID is correct and combat log returns UNIT_SPELLCAST_SUCCEEDED ,any idea for fix? thank you very much

**Comment by Relintai** [comment]
Definitely double check that the spell's id is actually 20589 ( https://github.com/Relintai/Relintais-Enemy-Kooldown-Tracker-WotLK/blob/ef84e92e9a894f761f1b4ccd5897b6540e4fe714/data/spells.lua#L43C46-L43C46 )

If the combatlog shows a SPELL_CAST_SUCCESS then it *should* work.

Now if the id is actually the same, since it's a custom spell script, maybe the server doesn't send the client who cast it, or sends a bogus caster.

You could try making it an interrupt, so it shows up on the interrupt bar as a dirty hack like so:

` [20589] = {105, nil, 105, 105, 105, 0, "", "defensive", false, true, false}, --Escape Artist `
